services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file:
      - ./.env.local
      - ./.env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - 'mysql_data:/mysql/data'

  application:
    image: node:22-alpine
    working_dir: /home/node
    command: sh -c "corepack enable && yarn set version berry && yarn install && yarn start"
    depends_on:
      - mysqldb
    restart: unless-stopped
    env_file:
      - ./.env.local
      - ./.env
    ports:
      - ${PORT}:${PORT}
    links:
      - mysqldb
    volumes:
      - ".:/home/node"

volumes:
   mysql_data:
     driver: local
